//! Hero marks: the pregenerated 16×10 team art the board paints, plus the
//! abbreviation fallback for teams whose art was never generated.

use crate::domain::Team;
use crate::theme;
use ratatui::layout::Rect;
use ratatui::style::{Modifier, Style};
use ratatui::widgets::Paragraph;
use ratatui::Frame;
use std::collections::HashMap;
use std::sync::OnceLock;

/// One cell of pregenerated logo art. `None` colors mean "terminal default":
/// no bg = transparent over the board, no fg on a space = nothing to draw.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ArtCell {
    pub ch: char,
    pub fg: Option<(u8, u8, u8)>,
    pub bg: Option<(u8, u8, u8)>,
}

/// A parsed 16×10 hero mark. Cells are (char, fg, bg); `width`/`height` are
/// the art's real extent after blank chafa padding rows are dropped.
pub struct HeroMark {
    rows: Vec<Vec<ArtCell>>,
    pub width: u16,
    pub height: u16,
}

impl HeroMark {
    /// The mark's cells, top row first. Tests read this to tell the two art
    /// sets apart; the blit walks it directly.
    pub fn rows(&self) -> &[Vec<ArtCell>] {
        &self.rows
    }
}

/// Parse chafa `-f symbols` output: truecolor SGR (38;2 / 48;2), reset (0),
/// default-color resets (39/49), reverse video (7/27), cursor hide/show noise.
fn parse_hero_mark(raw: &str) -> Option<HeroMark> {
    let mut rows: Vec<Vec<ArtCell>> = Vec::new();
    let mut row: Vec<ArtCell> = Vec::new();
    let mut fg: Option<(u8, u8, u8)> = None;
    let mut bg: Option<(u8, u8, u8)> = None;
    let mut reverse = false;
    let mut chars = raw.chars().peekable();
    while let Some(c) = chars.next() {
        match c {
            '\x1b' => {
                if chars.peek() != Some(&'[') {
                    continue;
                }
                chars.next();
                let mut seq = String::new();
                for c in chars.by_ref() {
                    if c.is_ascii_alphabetic() {
                        seq.push(c);
                        break;
                    }
                    seq.push(c);
                }
                let Some(final_byte) = seq.pop() else { continue };
                if final_byte != 'm' {
                    continue; // cursor hide/show etc.
                }
                let params: Vec<&str> = seq.split(';').collect();
                let mut i = 0;
                while i < params.len() {
                    match params[i] {
                        "" | "0" => {
                            fg = None;
                            bg = None;
                            reverse = false;
                        }
                        "7" => reverse = true,
                        "27" => reverse = false,
                        "39" => fg = None,
                        "49" => bg = None,
                        "38" | "48" if params.get(i + 1) == Some(&"2") && i + 4 < params.len() => {
                            let rgb = (
                                params[i + 2].parse().ok()?,
                                params[i + 3].parse().ok()?,
                                params[i + 4].parse().ok()?,
                            );
                            if params[i] == "38" {
                                fg = Some(rgb);
                            } else {
                                bg = Some(rgb);
                            }
                            i += 4;
                        }
                        _ => {}
                    }
                    i += 1;
                }
            }
            '\n' => {
                rows.push(std::mem::take(&mut row));
            }
            '\r' => {}
            ch => {
                let (mut cfg, mut cbg) = (fg, bg);
                if reverse {
                    std::mem::swap(&mut cfg, &mut cbg);
                }
                row.push(ArtCell { ch, fg: cfg, bg: cbg });
            }
        }
    }
    if !row.is_empty() {
        rows.push(row);
    }
    // Drop rows that draw nothing (chafa pads square art with blank lines).
    rows.retain(|r| r.iter().any(cell_visible));
    if rows.is_empty() {
        return None;
    }
    let width = rows.iter().map(|r| r.len()).max()? as u16;
    let height = rows.len() as u16;
    Some(HeroMark { rows, width, height })
}

fn cell_visible(c: &ArtCell) -> bool {
    if c.ch == ' ' {
        c.bg.is_some()
    } else {
        c.fg.is_some() || c.bg.is_some()
    }
}

/// Every bundled mark, key → raw chafa output. Compiled into the binary;
/// parsed at most once each (see [`hero_mark`]). The table is generated by
/// `tools/gen-logos.sh` alongside the art itself: `include_str!` needs
/// literal paths, and ~190 of them is not a list anyone keeps in sync by
/// hand.
#[path = "logo_sources.rs"]
mod sources;
use sources::{LIGHT_LOGO_SOURCES, LOGO_SOURCES};

/// The logo keys the binary ships art for, in embed order.
pub fn committed_keys() -> impl Iterator<Item = &'static str> {
    LOGO_SOURCES.iter().map(|(key, _)| *key)
}

/// The same keys, in the light set (v3.4 §7). The two sets carry the same
/// teams — `tools/gen-logos.sh` writes both from one pass.
pub fn light_keys() -> impl Iterator<Item = &'static str> {
    LIGHT_LOGO_SOURCES.iter().map(|(key, _)| *key)
}

/// The parsed marks, built on first use. Marks are blitted several times per
/// frame at up to 10 frames a second, and re-running the SGR parser over each
/// one every time was the mosaic's largest per-frame cost.
static ART: OnceLock<HashMap<&'static str, HeroMark>> = OnceLock::new();
static ART_LIGHT: OnceLock<HashMap<&'static str, HeroMark>> = OnceLock::new();

fn parsed(
    cell: &'static OnceLock<HashMap<&'static str, HeroMark>>,
    table: &'static [(&'static str, &'static str)],
) -> &'static HashMap<&'static str, HeroMark> {
    cell.get_or_init(|| {
        table
            .iter()
            .filter_map(|(key, raw)| Some((*key, parse_hero_mark(raw)?)))
            .collect()
    })
}

/// A ground this luminous is paper, and takes the light art. The threshold is
/// the midpoint of the WCAG relative-luminance range and nothing lives near
/// it: every dark ground gameday ships sits at or under gruvbox's `#282828`
/// (0.0185) and broadcast's black (0.0), while daygame's paper is 0.889.
const LIGHT_GROUND: f64 = 0.5;

/// The committed art for `logo_key` ("nfl/kc"), parsed once, from the set the
/// active theme's ground calls for. A light theme falls back to the standard
/// set for a key the light set somehow lacks — a mark drawn for the wrong
/// ground still beats a hole.
pub fn hero_mark(logo_key: &str) -> Option<&'static HeroMark> {
    if theme::rel_luma(theme::current().roles().ground) > LIGHT_GROUND {
        if let Some(mark) = parsed(&ART_LIGHT, LIGHT_LOGO_SOURCES).get(logo_key) {
            return Some(mark);
        }
    }
    parsed(&ART, LOGO_SOURCES).get(logo_key)
}

/// Blit `mark` centered into `area`, clipped to it, colors routed through
/// [`theme::Theme::art_color`].
pub fn draw_hero_mark(frame: &mut Frame, area: Rect, mark: &HeroMark) {
    if area.width == 0 || area.height == 0 {
        return;
    }
    let th = theme::current();
    let w = mark.width.min(area.width);
    let h = mark.height.min(area.height);
    let x0 = area.x + (area.width - w) / 2;
    let y0 = area.y + (area.height - h) / 2;
    let buf = frame.buffer_mut();
    for (y, row) in mark.rows.iter().take(h as usize).enumerate() {
        for (x, art_cell) in row.iter().take(w as usize).enumerate() {
            if !cell_visible(art_cell) {
                continue;
            }
            let cell = &mut buf[(x0 + x as u16, y0 + y as u16)];
            cell.set_char(art_cell.ch);
            cell.set_fg(art_cell.fg.map_or(th.fg, |(r, g, b)| th.art_color([r, g, b])));
            cell.set_bg(art_cell.bg.map_or(th.bg, |(r, g, b)| th.art_color([r, g, b])));
        }
    }
}

/// Missing mark: team abbreviation in team color, never a hole.
pub fn draw_abbr_mark(frame: &mut Frame, area: Rect, team: &Team) {
    let th = theme::current();
    let w = (team.abbr.chars().count() as u16 + 2).min(area.width);
    let slot = Rect {
        x: area.x + area.width.saturating_sub(w) / 2,
        y: area.y + area.height.saturating_sub(1) / 2,
        width: w,
        height: 1,
    };
    frame.render_widget(
        Paragraph::new(format!("⟨{}⟩", team.abbr)).style(
            Style::default()
                .fg(th.team_mark_color(team.color, team.alt_color))
                .add_modifier(Modifier::BOLD),
        ),
        slot,
    );
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unknown_key_is_none() {
        assert!(hero_mark("nfl/xyz").is_none());
    }

    #[test]
    fn parses_truecolor_and_reset() {
        let art = parse_hero_mark("\x1b[38;2;10;20;30mA\x1b[0mB\n").unwrap();
        assert_eq!(art.rows[0][0].ch, 'A');
        assert_eq!(art.rows[0][0].fg, Some((10, 20, 30)));
        assert_eq!(art.rows[0][1].fg, None);
    }

    #[test]
    fn reverse_video_swaps_colors() {
        let art = parse_hero_mark("\x1b[7m\x1b[38;2;1;2;3mX\n").unwrap();
        assert_eq!(art.rows[0][0].fg, None);
        assert_eq!(art.rows[0][0].bg, Some((1, 2, 3)));
    }

    /// Ruling R41: every bundled mark draws on a terminal that only has the
    /// quadrant blocks. The v3.2 art was generated with chafa's `sextant`
    /// class, whose U+1FB00–1FB3B range Terminal.app's default font does not
    /// cover — every mark was a field of tofu boxes there, and in the
    /// gallery's own PNG pipeline. `tools/gen-logos.sh` now defaults to
    /// `space+solid+half+quad`; this is what stops a regeneration from
    /// quietly putting the sextants back.
    #[test]
    fn no_bundled_mark_uses_a_symbol_outside_the_quadrant_blocks() {
        for (key, raw) in LOGO_SOURCES.iter().chain(LIGHT_LOGO_SOURCES) {
            let art = parse_hero_mark(raw).unwrap_or_else(|| panic!("{key} failed to parse"));
            for (y, row) in art.rows.iter().enumerate() {
                for (x, cell) in row.iter().enumerate() {
                    let o = cell.ch as u32;
                    assert!(
                        cell.ch == ' ' || (0x2580..=0x259F).contains(&o),
                        "{key} cell ({x},{y}) is U+{o:04X} ({:?}) — outside the quadrant range \
                         U+2580..=U+259F that every terminal draws",
                        cell.ch
                    );
                }
            }
        }
    }

    #[test]
    fn blank_padding_rows_are_dropped() {
        let art = parse_hero_mark(" \x1b[38;2;0;0;0m  \x1b[0m\n\x1b[38;2;9;9;9m#\n").unwrap();
        assert_eq!(art.height, 1);
        assert_eq!(art.rows[0][0].ch, '#');
    }
}
